import type { Metadata } from "next";
import { Geist, Geist_Mono, RocknRoll_One } from "next/font/google";
import "./globals.css";
import Navigation from "./components/nav";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rocknRoll = RocknRoll_One({
  weight: "400",
  variable: "--font-rocknroll",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rocknRoll.variable} antialiased flex min-h-screen flex-col`}
      >
        <Navigation />
        <main className="pt-16 flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
